### ISSUE TITLE
error while loading shared libraries: libapt-private.so.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yanruogu** [agile6v/container_cpu_detection#6]
environment:

kubernetes: v.1.11.10
docker:  17.09.1-ce
os: ubuntu 16.04

I use sysconf_test like this:
```
kubectl create configmap detection --from-file=./detection.so
kubectl create configmap sysconf --from-file=./sysconf_test
```
and then,deploy a pod：
```
kind: Deployment
metadata:
  name: test-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tag: lxcfs
        name: test-nginx
    spec:
      volumes:
        - name: detection
          configMap:
            name: detection
        - name: sysconf
          configMap:
             name: sysconf
      containers:
        - name: test-nginx
          image: openresty/openresty
          volumeMounts:
            - name: detection
              mountPath: /usr/lib
            - name: sysconf
              mountPath: /tmp
          resources:
            requests:
              cpu: "0.2"
              memory: "64Mi"
            limits:
              cpu: "1"
              memory: "128Mi"
```
when i login to pod, and execute command：
```
root@k8s-m:/home/www/server/kube-yamls/test# kubectl exec -it test-nginx-5c6bf4fb88-jlh74  /bin/bash 
root@test-nginx-5c6bf4fb88-jlh74:/# apt install procps
apt: error while loading shared libraries: libapt-private.so.0.0: cannot open shared object file: No such file or directory
```

this sysconf make something wrong

How can I fix it ？
